[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/functions/server/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 